#!/usr/bin/env bash
# Written by Eric Crosson
# 2017-01-12
# Version 0.0.0
#
# This program uses fzf to select a git repo to clone from a server.

# Currently only supports github

# TODO: ensure dependencies are installed

main() {
    local -r repo=$(./github-list-user-repos)
    [[ -z ${repos} ]] && exit -1
    git clone --recursive git@${git_server}:${username}/${repo}
}


main "$@"
